jobs:
  dependency-check:
    env:
      SCRIPT_DEPENDENCY: hugegraph-server/hugegraph-dist/scripts/dependency
      USE_STAGE: 'true'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      if: ${{ env.USE_STAGE == 'true' }}
      name: use staged maven repo settings
      run: 'cp $HOME/.m2/settings.xml /tmp/settings.xml

        mv -vf .github/configs/settings.xml $HOME/.m2/settings.xml

        '
    - continue-on-error: true
      name: mvn install
      run: 'mvn install -DskipTests=true -ntp

        '
    - continue-on-error: true
      name: generate current dependencies
      run: 'bash $SCRIPT_DEPENDENCY/regenerate_known_dependencies.sh current-dependencies.txt

        '
    - continue-on-error: true
      name: check third dependencies
      run: 'bash $SCRIPT_DEPENDENCY/check_dependencies.sh

        '
  dependency-review:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: critical
name: 3rd-party
on:
  repository_dispatch:
    types: trigger-ga___check-dependencies.yml
permissions:
  contents: read
