jobs:
  pd:
    env:
      REPORT_DIR: target/site/jacoco
      TRAVIS_DIR: hugegraph-server/hugegraph-dist/src/assembly/travis
      USE_STAGE: 'false'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - continue-on-error: true
      if: ${{ env.USE_STAGE == 'true' }}
      name: use staged maven repo settings
      run: 'cp $HOME/.m2/settings.xml /tmp/settings.xml

        mv -vf .github/configs/settings.xml $HOME/.m2/settings.xml

        '
    - continue-on-error: true
      name: Package
      run: 'mvn clean package -U -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
        -ntp

        '
    - continue-on-error: true
      name: Run common test
      run: 'mvn test -pl hugegraph-pd/hg-pd-test -am -P pd-common-test

        '
    - continue-on-error: true
      name: Run core test
      run: 'mvn test -pl hugegraph-pd/hg-pd-test -am -P pd-core-test

        '
    - continue-on-error: true
      name: Prepare env and service
      run: '$TRAVIS_DIR/start-pd.sh

        '
    - continue-on-error: true
      name: Run client test
      run: 'mvn test -pl hugegraph-pd/hg-pd-test -am -P pd-client-test

        '
    - continue-on-error: true
      name: Run rest test
      run: 'mvn test -pl hugegraph-pd/hg-pd-test -am -P pd-rest-test

        '
    - continue-on-error: true
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.0.0
      with:
        file: ${{ env.REPORT_DIR }}/*.xml
  store:
    env:
      REPORT_DIR: target/site/jacoco
      TRAVIS_DIR: hugegraph-server/hugegraph-dist/src/assembly/travis
      USE_STAGE: 'false'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - continue-on-error: true
      if: ${{ env.USE_STAGE == 'true' }}
      name: use staged maven repo settings
      run: 'cp $HOME/.m2/settings.xml /tmp/settings.xml

        mv -vf .github/configs/settings.xml $HOME/.m2/settings.xml

        '
    - continue-on-error: true
      name: Run common test
      run: 'mvn test -pl hugegraph-store/hg-store-test -am -P store-common-test

        '
    - continue-on-error: true
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.0.0
      with:
        file: ${{ env.REPORT_DIR }}/*.xml
name: hugegraph-pd-store-ci
on:
  repository_dispatch:
    types: trigger-ga___pd-store-ci.yml
