jobs:
  build:
    env:
      BACKEND: ${{ matrix.BACKEND }}
      BASE_BRANCH_NAME: ${{ github.base_ref }}
      HEAD_BRANCH_NAME: ${{ github.head_ref }}
      RAFT_MODE: ${{ startsWith(github.head_ref, 'test') || startsWith(github.head_ref,
        'raft') }}
      RELEASE_BRANCH: ${{ startsWith(github.ref_name, 'release-') || startsWith(github.ref_name,
        'test-') }}
      REPORT_DIR: target/site/jacoco
      TARGET_BRANCH_NAME: ${{ github.base_ref != '' && github.base_ref || github.ref_name
        }}
      TRAVIS_DIR: hugegraph-server/hugegraph-dist/src/assembly/travis
      TRIGGER_BRANCH_NAME: ${{ github.ref_name }}
      USE_STAGE: 'false'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - continue-on-error: true
      name: Install Java8 for backend
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      name: Prepare backend environment
      run: '$TRAVIS_DIR/install-backend.sh $BACKEND && jps -l

        '
    - continue-on-error: true
      name: Install Java ${{ matrix.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.JAVA_VERSION }}
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      if: ${{ env.USE_STAGE == 'true' }}
      name: Use staged maven repo settings
      run: 'cp $HOME/.m2/settings.xml /tmp/settings.xml

        cp -vf .github/configs/settings.xml $HOME/.m2/settings.xml && cat $HOME/.m2/settings.xml

        '
    - continue-on-error: true
      name: Compile
      run: 'mvn clean compile -U -Dmaven.javadoc.skip=true -ntp

        '
    - continue-on-error: true
      name: Run unit test
      run: '$TRAVIS_DIR/run-unit-test.sh $BACKEND

        '
    - continue-on-error: true
      name: Run core test
      run: '$TRAVIS_DIR/run-core-test.sh $BACKEND

        '
    - continue-on-error: true
      name: Run api test
      run: '$TRAVIS_DIR/run-api-test.sh $BACKEND $REPORT_DIR

        '
    - continue-on-error: true
      if: ${{ env.RAFT_MODE == 'true' && env.BACKEND == 'rocksdb' }}
      name: Run raft test
      run: '$TRAVIS_DIR/run-api-test-for-raft.sh $BACKEND $REPORT_DIR

        '
    - continue-on-error: true
      if: ${{ env.RELEASE_BRANCH == 'true' }}
      name: Run TinkerPop test
      run: '$TRAVIS_DIR/run-tinkerpop-test.sh $BACKEND tinkerpop

        '
    - continue-on-error: true
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ${{ env.REPORT_DIR }}/*.xml
        token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        BACKEND:
        - memory
        - rocksdb
        - hbase
        - cassandra
        - mysql
        - postgresql
        - scylladb
        JAVA_VERSION:
        - '11'
name: hugegraph-server-ci
on:
  repository_dispatch:
    types: trigger-ga___server-ci.yml
