jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v3
      with:
        days-before-issue-close: 20
        days-before-issue-stale: 15
        days-before-pr-close: 180
        days-before-pr-stale: 30
        delete-branch: false
        enable-statistics: true
        exempt-all-assignees: true
        exempt-all-milestones: true
        exempt-all-pr-milestones: true
        exempt-issue-labels: feature,bug,enhancement,improvement,todo,guide,doc,help
          wanted,security
        exempt-pr-labels: feature,bug,enhancement,improvement,todo,guide,doc,help
          wanted,security
        operations-per-run: 10
        remove-stale-when-updated: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: inactive
        stale-issue-message: Due to the lack of activity, the current issue is marked
          as stale and will be closed after 20 days, any update will remove the stale
          label
        stale-pr-label: inactive
        stale-pr-message: Due to the lack of activity, the current pr is marked as
          stale and will be closed after 180 days, any update will remove the stale
          label
        start-date: '2017-10-01T00:00:00Z'
name: Mark stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
